### ISSUE TITLE
Read the access.log file and return a dataframe

### ISSUE THREAD

**Issue by icaoberg** [brain-image-library/py-brain-logs#1]
Create a function that reads the the access.log and returns a dataframe.

If you want to avoid adding columns to the database, then let me know why.

If you think we need more columns than

* date
* IP
* dataset
* number of downloads

then let me know.

**Comment by francojoshua** [comment]
@icaoberg I have created a dataframe that includes the following keys:

`Index(['ip', 'date', 'method', 'url', 'status_code', 'size'], dtype='object')`

This, however, is based on each row being a line in the log file. According to the README, it seems like that isn't your vision. My question for you is how would we include an 'ip' column if a dataset could be requested by multiple ip addresses?

**Comment by francojoshua** [comment]
@icaoberg I have uploaded a Juypter notebook to this branch. All of the other issues will require tabular data, so I think it might be a good idea to fix anything we want to fix and push this to master, so all of the other branches will reflect that.

Let me know what you think and I would be happy to open a pull request.
